### ISSUE TITLE
GPU operator failing to deploy due to mirrorlist.centos.org resolution error

### ISSUE THREAD

**Issue by jesse-gonzalez** [jesse-gonzalez/nai-llm-fleet-infra#11]
Centos EOL'ed mirrorlist, so need workaround.

**Comment by jesse-gonzalez** [comment]
added following config map and helm chart values
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: repo-config
  namespace: gpu-operator
data:
  CentOS-Base.repo: |
    [base]
    name=CentOS-$releasever - Base - Vault
    baseurl=https://vault.centos.org/7.9.2009/os/x86_64/
    gpgcheck=0
    enabled=1

    [updates]
    name=CentOS-$releasever - Updates - Vault
    baseurl=https://vault.centos.org/7.9.2009/updates/x86_64/
    gpgcheck=0
    enabled=1 
``` 

helm-chart-values

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: flux-system
spec:
  values:
    driver:
      repoConfig:
        configMapName: repo-config
```
